services:
  tennis-tracker:
    build: .
    container_name: realtime-tennis-shot-analysis
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=
    command: streamlit run src/Home.py --server.port=8080 --server.address=0.0.0.0